export const filters = {
  equals: 'Равно',
  equalsAbbr: '=',
  notEqual: 'Не равно',
  notEqualAbbr: '!=',
  lessThan: 'Меньше',
  lessThanAbbr: '<',
  lessThanOrEqual: 'Меньше или равно',
  lessThanOrEqualAbbr: '<=',
  greaterThan: 'Больше',
  greaterThanAbbr: '>',
  greaterThanOrEqual: 'Больше или равно',
  greaterThanOrEqualAbbr: '>=',
  between: 'Между',
  betweenAbbr: '<>',
  contains: 'Содержит',
  startsWith: 'Начинается с',
  endsWith: 'Заканчивается на',
  like: 'Содержит',
  notEmpty: 'Не пустая',
  empty: 'Пустая',
  includeAny: 'Любой из элементов',
  includeAll: 'Все из элементов',
  includeEquals: 'Только эти элементы',
  includeNone: 'Ни один из элементов'
};
